---
- name: Install the 'Gnome desktop' environment group
  yum:
    name: "{{ rhel_desktop_packages }}"
    state: present

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
